/* ==========================================================================
   VUGANA — Translations (i18n)
   NOTE: The Kinyarwanda text below is a best-effort draft for demo purposes.
   Given this app supports GBV survivors, please have a native Kinyarwanda
   speaker (ideally with GBV-support experience) review and correct this
   before any real-world use — mistranslation here could confuse or
   discourage someone in crisis.
   ========================================================================== */

const I18N = {
  en: {
    "nav.hotline": "Emergency Toll-Free: 116",
    "nav.tagline": "Speak Out — Rwanda GBV Portal",
    "nav.quick_exit": "Quick Exit ✖",
    "nav.home": "Home",
    "nav.report": "Report Anonymously",
    "nav.track": "Track Report",
    "nav.centres": "Isange Centres",
    "nav.rights": "Rights & Guide",
    "nav.staff": "Isange Staff Portal",
    "nav.about": "About",

    "hero.badge": "Confidential • Safe • Free",
    "hero.title": "Break the Silence. Report Safely & Anonymously in Rwanda.",
    "hero.subtitle": "Vugana ('Speak Out') enables GBV survivors and witnesses in Rwanda to report incidents without logging in, track report responses using a secret code, and access nearest Isange One Stop Support Centres.",
    "hero.cta_report": "Report Incident Now",
    "hero.cta_track": "Track Existing Report",
    "hero.cta_rights": "Know Your Legal Rights",

    "stats.stat1_num": "100%", "stats.stat1_text": "Anonymous & Confidential",
    "stats.stat2_num": "30", "stats.stat2_text": "Districts Covered in Rwanda",
    "stats.stat3_num": "24/7", "stats.stat3_text": "Free Isange Support",
    "stats.stat4_num": "116", "stats.stat4_text": "National Emergency Hotline",

    "report_form.title": "Anonymous GBV Incident Report",
    "report_form.desc": "You do NOT need to give your name or phone number. Your safety and privacy are fully protected under Rwandan law.",
    "report_form.step1_title": "1. Incident Location",
    "report_form.step2_title": "2. Incident Details",
    "report_form.type_label": "Type of Abuse *",
    "report_form.date_label": "Incident Date *",
    "report_form.time_label": "Incident Time",
    "report_form.desc_label": "Describe What Happened *",
    "report_form.desc_placeholder": "Provide as much detail as you feel comfortable sharing...",
    "report_form.step3_title": "3. Optional Contact Info (Voluntary)",
    "report_form.contact_notice": "Leaving these blank keeps your report 100% anonymous.",
    "report_form.name_placeholder": "Your Name (Optional)",
    "report_form.phone_placeholder": "Your Phone Number (Optional)",
    "report_form.submit_btn": "Submit Anonymous Report Securely",
    "report_form.success_title": "Report Submitted Successfully!",
    "report_form.code_heading": "YOUR SECRET TRACKING CODE:",
    "report_form.code_warning": "IMPORTANT: Save or copy this code! It is the ONLY way you can return later to check updates and responses from Isange One Stop Centre staff.",
    "report_form.track_now_btn": "Check Status Now",

    "tracking.title": "Track Your GBV Report",
    "tracking.subtitle": "Enter your confidential tracking code (e.g. VGN-482910) to view official responses, assigned Isange social workers, and progress updates.",
    "tracking.search_btn": "Find Report",
    "tracking.timeline_title": "Case Resolution Timeline & Messages",

    "centres_page.title": "Find Nearby Isange One Stop Centre",
    "centres_page.subtitle": "Isange One Stop Centres provide 24/7 free medical care, trauma counseling, forensic evidence collection, safe shelter, and legal support across Rwanda's 30 districts.",
    "centres_page.filter_label": "Filter by District:",

    "rights_page.title": "Know Your Rights & GBV Legal Protections in Rwanda",
    "rights_page.subtitle": "Empower yourself with clear information on Law N°68/2018, survivor rights, emergency steps, and self-assessment tools.",
    "rights_page.tab_rights": "Your Legal Rights",
    "rights_page.tab_abuse_quiz": "Is This Abuse? (Self Check)",
    "rights_page.tab_faq": "FAQs",
    "rights_page.law_intro": "Under Rwandan Law N°68/2018 of 30/08/2018 on prevention and punishment of Gender-Based Violence:",
    "rights_page.right1_title": "1. Right to Confidential & Free Medical Care",
    "rights_page.right1_desc": "Every survivor of physical or sexual violence has the right to immediate, free emergency medical treatment, PEP (Post-Exposure Prophylaxis within 72 hours), and injury documentation.",
    "rights_page.right2_title": "2. Right to Privacy and Anonymity",
    "rights_page.right2_desc": "The law strictly forbids exposing the identity of a GBV victim in media or public records without explicit consent.",
    "rights_page.right3_title": "3. Right to Legal Defense & Justice",
    "rights_page.right3_desc": "GBV is a public crime in Rwanda. The Rwanda Investigation Bureau (RIB) and Prosecution handle cases free of charge.",
    "rights_page.right4_title": "4. Right to Psychosocial Counseling & Safe Shelter",
    "rights_page.right4_desc": "Isange One Stop Centres provide free professional mental health therapy and temporary emergency protection.",
    "rights_page.quiz_title": "Self-Assessment: Identifying Abuse",
    "rights_page.quiz_desc": "Violence is not always physical. Select any statement below that applies to your situation:",
    "rights_page.quiz_alert_title": "If you answered YES to any of these statements:",
    "rights_page.quiz_alert_desc": "You are experiencing Gender-Based Violence. You are NOT alone, and it is NOT your fault. Help is available free of charge 24/7.",
    "rights_page.faq1_q": "Can I report if I am not sure I want to go to court?",
    "rights_page.faq1_a": "Yes! Submitting an anonymous report on Vugana allows Isange staff to offer medical and psychological support without forcing legal charges if you are not ready.",
    "rights_page.faq2_q": "Does Vugana cost any money to use?",
    "rights_page.faq2_a": "No. Vugana is 100% free to access on any mobile phone or computer.",
    "rights_page.faq3_q": "What happens if someone opens my browser while I am using Vugana?",
    "rights_page.faq3_a": "Use the red 'Quick Exit' button at the top of the page. It will immediately redirect your screen to a neutral website.",

    "staff_portal.title": "Isange One Stop Centre Staff Portal",
    "staff_portal.subtitle": "Authorized login for Isange social workers, medical officers, and RIB liaison officers to review district reports and update case progress.",
    "staff_portal.role_label": "I am logging in as:",
    "staff_portal.passcode_label": "Enter Staff Access Passcode:",
    "staff_portal.login_btn": "Access Dashboard",
    "staff_portal.total_reports": "Total Reports:",
    "staff_portal.district_filter": "Filter by District:",
    "staff_portal.status_filter": "Filter by Status:",
    "staff_portal.status_update_label": "Update Report Status:",
    "staff_portal.message_label": "Staff Note / Action Taken for Survivor:",
    "staff_portal.message_placeholder": "e.g. Medical examination arranged at District Hospital. Social worker assigned. Please contact Hotline 116...",
    "staff_portal.submit_response_btn": "Send Response to Tracking Code"
  },

  rw: {
    "nav.hotline": "Nomero y'ubufasha ku buntu: 116",
    "nav.tagline": "Vugana — Urubuga rw'u Rwanda rw'Ihohoterwa Rishingiye ku Gitsina",
    "nav.quick_exit": "Sohoka Vuba ✖",
    "nav.home": "Ahabanza",
    "nav.report": "Tanga Raporo mu Ibanga",
    "nav.track": "Kurikirana Raporo",
    "nav.centres": "Ibigo Isange",
    "nav.rights": "Uburenganzira n'Ubuyobozi",
    "nav.staff": "Urubuga rw'Abakozi ba Isange",
    "nav.about": "Ibiranga Iyi Porogaramu",

    "hero.badge": "Ibanga • Umutekano • Ku Buntu",
    "hero.title": "Vugana. Tanga Raporo mu Mutekano no mu Ibanga mu Rwanda.",
    "hero.subtitle": "Vugana ifasha abarokotse n'abahamya b'ihohoterwa rishingiye ku gitsina mu Rwanda gutanga raporo batinjiye, gukurikirana raporo bakoresheje kode y'ibanga, no kubona Ibigo Isange biri hafi yabo.",
    "hero.cta_report": "Tanga Raporo Nonaha",
    "hero.cta_track": "Kurikirana Raporo Wamaze Gutanga",
    "hero.cta_rights": "Menya Uburenganzira Bwawe",

    "stats.stat1_num": "100%", "stats.stat1_text": "Ibanga Ryuzuye",
    "stats.stat2_num": "30", "stats.stat2_text": "Uturere twose two mu Rwanda",
    "stats.stat3_num": "24/7", "stats.stat3_text": "Ubufasha bwa Isange ku Buntu",
    "stats.stat4_num": "116", "stats.stat4_text": "Nomero y'Ubutabazi Bw'Igihugu",

    "report_form.title": "Raporo y'Ihohoterwa mu Ibanga",
    "report_form.desc": "Ntibisabwa kwerekana izina cyangwa nomero ya telefoni. Umutekano n'ibanga ryawe birarindwa n'amategeko y'u Rwanda.",
    "report_form.step1_title": "1. Aho Ibyabaye",
    "report_form.step2_title": "2. Ibisobanuro by'Ibyabaye",
    "report_form.type_label": "Ubwoko bw'Ihohoterwa *",
    "report_form.date_label": "Itariki Byabereyeho *",
    "report_form.time_label": "Isaha Byabereyeho",
    "report_form.desc_label": "Sobanura Ibyabaye *",
    "report_form.desc_placeholder": "Tanga amakuru menshi uko wumva ubishoboye...",
    "report_form.step3_title": "3. Amakuru y'Ukwifashisha (Ntabwo asabwa)",
    "report_form.contact_notice": "Kubisiga ubusa bituma raporo yawe iguma mu ibanga burundu.",
    "report_form.name_placeholder": "Izina Ryawe (Ntabwo risabwa)",
    "report_form.phone_placeholder": "Telefoni Yawe (Ntabwo isabwa)",
    "report_form.submit_btn": "Ohereza Raporo mu Mutekano",
    "report_form.success_title": "Raporo Yoherejwe Neza!",
    "report_form.code_heading": "KODE YAWE Y'IBANGA:",
    "report_form.code_warning": "NGENZI: Bika cyangwa wandike iyi kode! Ni yo nzira yonyine yo kugaruka gukurikirana igisubizo cy'abakozi ba Isange.",
    "report_form.track_now_btn": "Reba Aho Bigeze Nonaha",

    "tracking.title": "Kurikirana Raporo Yawe",
    "tracking.subtitle": "Andika kode y'ibanga (urugero: VGN-482910) kugira ngo urebe igisubizo cy'abakozi, umukozi wagenewe, n'aho raporo igeze.",
    "tracking.search_btn": "Shakisha Raporo",
    "tracking.timeline_title": "Aho Raporo Igeze n'Ubutumwa",

    "centres_page.title": "Shakisha Ikigo Isange Kikwegereye",
    "centres_page.subtitle": "Ibigo Isange bitanga ubuvuzi ku buntu, ubujyanama, gukusanya ibimenyetso, ubuhungiro, n'ubufasha mu by'amategeko mu turere twose 30 tw'u Rwanda, amasaha 24/7.",
    "centres_page.filter_label": "Hitamo Akarere:",

    "rights_page.title": "Menya Uburenganzira Bwawe n'Amategeko arengera abarokotse",
    "rights_page.subtitle": "Menya amakuru ajyanye n'Itegeko N°68/2018, uburenganzira bw'abarokotse, ibikorwa byihutirwa, n'ibikoresho byo kwisuzuma.",
    "rights_page.tab_rights": "Uburenganzira Bwawe",
    "rights_page.tab_abuse_quiz": "Ese Iri ni Ihohoterwa? (Kwisuzuma)",
    "rights_page.tab_faq": "Ibibazo Bikunze Kubazwa",
    "rights_page.law_intro": "Hakurikijwe Itegeko N°68/2018 ryo ku wa 30/08/2018 rirengera abarokotse ihohoterwa rishingiye ku gitsina:",
    "rights_page.right1_title": "1. Uburenganzira bwo Kuvurwa mu Ibanga no ku Buntu",
    "rights_page.right1_desc": "Umurokotse w'ihohoterwa ry'umubiri cyangwa iry'imibonano mpuzabitsina afite uburenganzira bwo kuvurwa vuba ku buntu, gufata PEP mu masaha 72, no kwandikirwa ibimenyetso.",
    "rights_page.right2_title": "2. Uburenganzira ku Bwigenge n'Ibanga",
    "rights_page.right2_desc": "Amategeko abuza rikomeye kumenyekanisha uwarenganyijwe mu itangazamakuru cyangwa mu nyandiko za Leta atabyemeye.",
    "rights_page.right3_title": "3. Uburenganzira bwo Kuburanira no Kuboneza Ubutabera",
    "rights_page.right3_desc": "Ihohoterwa rishingiye ku gitsina ni icyaha giteganywa n'amategeko. Urwego rw'Igihugu rushinzwe iperereza (RIB) n'Ubushinjacyaha bikorera ku buntu.",
    "rights_page.right4_title": "4. Uburenganzira ku Bujyanama n'Ubuhungiro",
    "rights_page.right4_desc": "Ibigo Isange bitanga ubujyanama bw'ababigize umwuga ku buntu n'ubuhungiro by'igihe gito.",
    "rights_page.quiz_title": "Kwisuzuma: Kumenya Ihohoterwa",
    "rights_page.quiz_desc": "Ihohoterwa ntabwo buri gihe riba ku mubiri. Hitamo ibibazo byose bikubera:",
    "rights_page.quiz_alert_title": "Niba wasubije YEGO ku kimwe muri ibi:",
    "rights_page.quiz_alert_desc": "Uri kurenganywa. Ntabwo uri wenyine, kandi ntabwo ari ikosa ryawe. Ubufasha buraboneka ku buntu amasaha 24/7.",
    "rights_page.faq1_q": "Ese nshobora gutanga raporo ntanashaka kujya mu rukiko?",
    "rights_page.faq1_a": "Yego! Gutanga raporo mu ibanga kuri Vugana bituma abakozi ba Isange bagufasha mu buvuzi n'ubujyanama nta gahato ko gushinja mu rukiko igihe utaritegura.",
    "rights_page.faq2_q": "Ese Vugana isaba amafaranga?",
    "rights_page.faq2_a": "Oya. Vugana ikoreshwa ku buntu burundu kuri telefoni cyangwa mudasobwa iyo ari yo yose.",
    "rights_page.faq3_q": "Bite se niba hari umuntu ufunguye porogaramu igihe nkoresha Vugana?",
    "rights_page.faq3_a": "Koresha buto itukura yanditseho 'Sohoka Vuba' iri hejuru y'urupapuro. Izahita ikwohereza ku rundi rubuga rutagira icyo ruvuze.",

    "staff_portal.title": "Urubuga rw'Abakozi ba Isange",
    "staff_portal.subtitle": "Kwinjira kwemewe ku bakozi ba Isange, abaganga, n'abahuza ba RIB kugira ngo basuzume raporo z'uturere no kuvugurura aho zigeze.",
    "staff_portal.role_label": "Ninjira nk'uwuhe:",
    "staff_portal.passcode_label": "Andika Ijambo ry'Ibanga ry'Umukozi:",
    "staff_portal.login_btn": "Injira mu Rubuga",
    "staff_portal.total_reports": "Umubare wa Raporo:",
    "staff_portal.district_filter": "Hitamo Akarere:",
    "staff_portal.status_filter": "Hitamo Aho Bigeze:",
    "staff_portal.status_update_label": "Vugurura Aho Raporo Igeze:",
    "staff_portal.message_label": "Ubutumwa bw'Umukozi / Icyakozwe:",
    "staff_portal.message_placeholder": "urugero: Isuzuma ryateganyijwe ku Bitaro by'Akarere. Umukozi w'imibereho myiza yagenwe. Hamagara 116...",
    "staff_portal.submit_response_btn": "Ohereza Igisubizo kuri Kode"
  }
};
