/**
 * VUGANA Internationalization (i18n) & Educational Content
 * Supports English (EN) and Kinyarwanda (RW)
 */

const I18N_DATA = {
  en: {
    nav: {
      brand: "VUGANA",
      tagline: "Speak Out — Rwanda GBV Portal",
      home: "Home",
      report: "Report Anonymously",
      track: "Track Report",
      centres: "Isange Centres",
      rights: "Rights & Abuse Guide",
      staff: "Isange Staff Portal",
      quick_exit: "Quick Exit ✖",
      hotline: "Emergency Toll-Free: 116"
    },
    hero: {
      badge: "Confidential • Safe • Free",
      title: "Break the Silence. Report Safely & Anonymously in Rwanda.",
      subtitle: "Vugana ('Speak Out') enables GBV survivors and witnesses in Rwanda to report incidents without logging in, track report responses using a secret code, and access nearest Isange One Stop Support Centres.",
      cta_report: "Report Incident Now",
      cta_track: "Track Existing Report",
      cta_rights: "Know Your Legal Rights"
    },
    stats: {
      stat1_num: "100%",
      stat1_text: "Anonymous & Confidential",
      stat2_num: "30",
      stat2_text: "Districts Covered in Rwanda",
      stat3_num: "24/7",
      stat3_text: "Free Isange Support",
      stat4_num: "116",
      stat4_text: "National Emergency Hotline"
    },
    report_form: {
      title: "Anonymous GBV Incident Report",
      desc: "You do NOT need to give your name or phone number. Your safety and privacy are fully protected under Rwandan law.",
      step1_title: "1. Incident Location",
      district_label: "Select District in Rwanda *",
      district_select_default: "-- Select District --",
      step2_title: "2. Incident Details",
      type_label: "Type of Abuse *",
      type_options: [
        "Physical Violence (Hitting, Assault, Battery)",
        "Sexual Violence (Rape, Sexual Harassment, Coercion)",
        "Emotional / Psychological Abuse (Threats, Intimidation, Stalking)",
        "Spousal / Domestic Violence (Partner Abuse)",
        "Economic Violence (Deprivation of basic resources)",
        "Child Abuse / Exploitation"
      ],
      date_label: "Approximate Incident Date *",
      time_label: "Approximate Time (Optional)",
      desc_label: "Describe What Happened *",
      desc_placeholder: "Provide as much detail as you feel comfortable sharing (e.g. location details, nature of abuse, immediate risk). Do not include personal identity unless you wish to.",
      step3_title: "3. Optional Contact Info (Voluntary)",
      contact_notice: "Leaving these blank keeps your report 100% anonymous.",
      name_label: "Your Name (Optional)",
      name_placeholder: "e.g. Jeanine M. or leave blank",
      phone_label: "Your Phone / WhatsApp Number (Optional)",
      phone_placeholder: "e.g. 0788XXXXXX or leave blank",
      submit_btn: "Submit Anonymous Report Securely",
      success_title: "Report Submitted Successfully!",
      code_heading: "YOUR SECRET TRACKING CODE:",
      code_warning: "IMPORTANT: Save or copy this code! It is the ONLY way you can return later to check updates and responses from Isange One Stop Centre staff.",
      track_now_btn: "Check Status Now"
    },
    tracking: {
      title: "Track Your GBV Report",
      subtitle: "Enter your confidential tracking code (e.g. VGN-482910) to view official responses, assigned Isange social workers, and progress updates.",
      code_label: "Secret Tracking Code *",
      code_placeholder: "e.g. VGN-482910",
      search_btn: "Find Report",
      status_label: "Current Report Status:",
      assigned_label: "Assigned Support Centre:",
      submitted_date: "Submitted Date:",
      timeline_title: "Case Resolution Timeline & Messages",
      no_history: "No responses logged yet by Isange Centre staff. Please check back soon.",
      error_not_found: "No report found matching this tracking code. Please verify and try again."
    },
    centres_page: {
      title: "Find Nearby Isange One Stop Centre",
      subtitle: "Isange One Stop Centres provide 24/7 free medical care, trauma counseling, forensic evidence collection, safe shelter, and legal support in all 44 hospital locations across Rwanda's 30 districts.",
      filter_label: "Filter by District:",
      all_districts: "All Districts",
      call_now: "Call Hotline 116",
      direct_call: "Direct Phone:",
      police_station: "Local RIB / Police Unit:",
      services_offered: "Available Services:"
    },
    rights_page: {
      title: "Know Your Rights & GBV Legal Protections in Rwanda",
      subtitle: "Empower yourself with clear information on Law N°68/2018, survivor rights, emergency steps, and self-assessment tools.",
      tab_rights: "Your Legal Rights",
      tab_abuse_quiz: "Is This Abuse? (Self Check)",
      tab_faq: "Frequently Asked Questions",
      law_intro: "Under Rwandan Law N°68/2018 of 30/08/2018 on prevention and punishment of Gender-Based Violence:",
      right1_title: "1. Right to Confidential & Free Medical Care",
      right1_desc: "Every survivor of physical or sexual violence has the right to immediate, free emergency medical treatment, PEP (Post-Exposure Prophylaxis within 72 hours), and injury documentation at any health facility or Isange Centre.",
      right2_title: "2. Right to Privacy and Anonymity",
      right2_desc: "The law strictly forbids exposing the identity of a GBV victim in media or public records without explicit consent. You have the right to report anonymously.",
      right3_title: "3. Right to Legal Defense & Justice",
      right3_desc: "GBV is a public crime in Rwanda. The Rwanda Investigation Bureau (RIB) and Prosecution will handle your case without charging court fees.",
      right4_title: "4. Right to Psychosocial Counseling & Safe Shelter",
      right4_desc: "Isange One Stop Centres provide free professional mental health therapy and temporary emergency protection if you are facing immediate home danger.",
      quiz_title: "Self-Assessment: Identifying Abuse",
      quiz_desc: "Violence is not always physical. Select any statement below that applies to your situation:",
      quiz_items: [
        "Does your partner or family member physically hit, slap, push, or threaten you?",
        "Are you forced into sexual acts against your will or without consent?",
        "Does someone control all your money, prevent you from working, or deny food/basic needs?",
        "Are you constantly insulted, humiliated, threatened, or isolated from friends/family?",
        "Are you being stalked, monitored digitally, or threatened with public shame?"
      ],
      quiz_alert_title: "If you answered YES to any of these statements:",
      quiz_alert_desc: "You are experiencing Gender-Based Violence. You are NOT alone, and it is NOT your fault. Help is available free of charge 24/7.",
      faq1_q: "Can I report if I am not sure I want to go to court?",
      faq1_a: "Yes! Submitting an anonymous report on Vugana allows Isange staff to offer medical and psychological support without forcing legal charges if you are not ready.",
      faq2_q: "Does Vugana cost any money to use?",
      faq2_a: "No. Vugana is 100% free to access on any mobile phone or computer.",
      faq3_q: "What happens if someone opens my browser while I am using Vugana?",
      faq3_a: "Use the red 'Quick Exit' button at the top of the page. It will immediately redirect your screen to a neutral website."
    },
    staff_portal: {
      title: "Isange One Stop Centre Staff Portal",
      subtitle: "Authorized login for Isange social workers, medical officers, and RIB liaison officers to review district reports and update case progress.",
      passcode_label: "Enter Staff Access Passcode:",
      passcode_placeholder: "Default: isange2026",
      login_btn: "Access Staff Dashboard",
      district_filter: "Filter Reports by District:",
      status_filter: "Filter by Status:",
      total_reports: "Total Reports Managed:",
      respond_title: "Post Official Staff Response & Update Status",
      message_label: "Staff Note / Action Taken for Survivor:",
      message_placeholder: "e.g. Medical examination arranged at District Hospital. Social worker assigned. Please contact Hotline 116 for urgent transport.",
      status_update_label: "Update Report Status:",
      submit_response_btn: "Send Response to Tracking Code"
    }
  },
  rw: {
    nav: {
      brand: "VUGANA",
      tagline: "Vugana — Urubuga rwo Gutanga Raporo ku Ihohoterwa mu Rwanda",
      home: "Ahabanza",
      report: "Tanga Raporo mu Ibanga",
      track: "Kurikirana Raporo",
      centres: "Ikusanyirizo rya Isange",
      rights: "Uburenganzira bwawe",
      staff: "Ahabarizwa Abakozi ba Isange",
      quick_exit: "Sohoka Wihuse ✖",
      hotline: "Umurongo utishyurwa: 116"
    },
    hero: {
      badge: "Mu Ibanga • Umutekano • Ku Buntu",
      title: "Vuga Ukuvari. Tanga Raporo mu Ibanga n'Umutekano mu Rwanda.",
      subtitle: "Vugana ifasha abakorewe ihohoterwa n'ababyabonye gutanga raporo batarinze kwerekana imyirondoro yabo, bagakurikirana aho ikirego kigeze bakoresheje ikode ry'ibanga.",
      cta_report: "Tanga Raporo Sawa",
      cta_track: "Kurikirana Raporo Yawe",
      cta_rights: "Omenya Uburenganzira Bwawe"
    },
    stats: {
      stat1_num: "100%",
      stat1_text: "Ibanga n'Umutekano",
      stat2_num: "30",
      stat2_text: "Uturere Twose tw'u Rwanda",
      stat3_num: "24/7",
      stat3_text: "Ubufasha bwa Isange ku Buntu",
      stat4_num: "116",
      stat4_text: "Umurongo utishyurwa wa Polisi"
    },
    report_form: {
      title: "Fomu yo Gutanga Raporo y'Ihohoterwa mu Ibanga",
      desc: "NTUBWIRIZA gutanga izina cyangwa nimero ya terefone. Umutekano n'ibanga byawe birarinzwe mu mategeko y'u Rwanda.",
      step1_title: "1. Aho Ihohoterwa Ryabereye",
      district_label: "Hitamo Akarere mu Rwanda *",
      district_select_default: "-- Hitamo Akarere --",
      step2_title: "2. Ibirambuye ku Ihohoterwa",
      type_label: "Ubwoko bw'Ihohoterwa *",
      type_options: [
        "Ihohoterwa rishingiye ku mubiri (Kukubita, Gukomeretsa)",
        "Ihohoterwa rishingiye ku gitsina (Gufata ku ngufu, Gukurura ku ngufu)",
        "Ihohoterwa mu mutwe / mu bitekerezo (Kukangisha, Kutesha umutwe)",
        "Ihohoterwa ryo mu rugo / ku bashakanye",
        "Ihohoterwa rishingiye ku mutungo (Kunyaga ibitunga umuryango)",
        "Ihohoterwa rikorerwa abana"
      ],
      date_label: "Itariki ryabereyeho *",
      time_label: "Isaha (Niba uyizi)",
      desc_label: "Sobanura ibyabaye *",
      desc_placeholder: "Sobanura mu magambo yawe ibyabaye, aho ryabereye, n'uburyo bwakoreshejwe. Ntubwirizwa kwandika izina ryawe.",
      step3_title: "3. Izina no Kuvugana (Ubyishakiye)",
      contact_notice: "Kutabyandika biha raporo yawe ibanga rya 100%.",
      name_label: "Izina ryawe (Ubyishakiye)",
      name_placeholder: "Ugereranyo: Jeanine M.",
      phone_label: "Nimero ya Terefone / WhatsApp (Ubyishakiye)",
      phone_placeholder: "Ugereranyo: 0788XXXXXX",
      submit_btn: "Ohereza Raporo mu Ibanga",
      success_title: "Raporo Yawe Yoherejwe Neza!",
      code_heading: "IKODE RYAWE RY'IBANGA RYO KURIKIRANA:",
      code_warning: "ICYO KWITONDERWA: Bika cyangwa wandike iyi kode! Ni yo yonyine uzakoresha ugaruka kureba igisubizo cy'abakozi ba Isange One Stop Centre.",
      track_now_btn: "Reba aho ikirego kigeze"
    },
    tracking: {
      title: "Kurikirana Raporo Yerekeye Ihohoterwa",
      subtitle: "Shyiramo kode yawe y'ibanga (urugero: VGN-482910) kureba ibisubizo n'ubufasha uteganyirijwe n'abakozi ba Isange.",
      code_label: "Ikode y'Ibanga *",
      code_placeholder: "Urugero: VGN-482910",
      search_btn: "Shakisha Raporo",
      status_label: "Aho Raporo Igeze:",
      assigned_label: "Ikusanyirizo rya Isange Riyirimo:",
      submitted_date: "Itariki Yoherejweho:",
      timeline_title: "Amakuru n'Ibisubizo by'Abakozi ba Isange",
      no_history: "Nta nshuro abakozi ba Isange barabyandikaho. Urashobora kureba gake gake.",
      error_not_found: "Nta raporo ibonetse kuri iyi kode. Nyamuneka reba niba wayanditse neza."
    },
    centres_page: {
      title: "Shaka Ikusanyirizo rya Isange Riri Hafi Yabaye",
      subtitle: "Amakusanyirizo ya Isange One Stop Centre atanga ubuvuzi, inshunge mu bitekerezo, ubufasha mu mategeko n'icumbi ry'ingoboka ku buntu mu bitaro byose 44 mu turere 30 tw'u Rwanda.",
      filter_label: "Hitamo Akarere:",
      all_districts: "Uturere Twose",
      call_now: "Hamagara 116 (Ku Buntu)",
      direct_call: "Terefone Zihuse:",
      police_station: "Station ya Polisi / RIB:",
      services_offered: "Services Zitangwa:"
    },
    rights_page: {
      title: "Manya Uburenganzira Bwawe n'Amategeko mu Rwanda",
      subtitle: "Soma Itegeko N°68/2018 rihana ihohoterwa rishingiye ku gitsina n'uburyo wakwikura mu kaga.",
      tab_rights: "Uburenganzira mu Mategeko",
      tab_abuse_quiz: "Ese Iri ni Ihohoterwa? (Isuzume)",
      tab_faq: "Ibibazo Bikunze Kubazwa",
      law_intro: "Mu mategeko y'u Rwanda N°68/2018 ryo ku wa 30/08/2018 ryerekeye kumvira no guhana ihohoterwa rishingiye ku gitsina:",
      right1_title: "1. Uburenganzira bwo Gukorerwa Ubuvuzi mu Ibanga n'ku Buntu",
      right1_desc: "Umuntu wese wakorewe ihohoterwa afite uburenganzira bwo kwitabwaho mu bitaro no guhabwa imiti igabanya ibyago byo kwandura SIDA (PEP mu masaha 72) ku buntu.",
      right2_title: "2. Uburenganzira bwo Kurindwa Izina n'Ibanga",
      right2_desc: "Amategeko aziririza kumvikanisha izina cyangwa isura y'uwakorewe ihohoterwa mu binyamakuru cyangwa ku karubanda utabyemerewe.",
      right3_title: "3. Uburenganzira bwo Kuhabwa Ubutabera",
      right3_desc: "Ihohoterwa rishingiye ku gitsina ni icyaha cyo mu rwego rwa rusange. Urwego rw'Igihugu rw'Ubugenzacyaha (RIB) n'Ubushinjacyaha babikurikirana ku buntu.",
      right4_title: "4. Uburenganzira bwo Kuhabwa Counselors n'Icumbi",
      right4_desc: "Isange One Stop Centre iguha abahanga mu by'imitekerereze n'icumbi ry'ingoboka niba uri mu kaga mu rugo.",
      quiz_title: "Isuzume: Kumenya niba Urikorerwa Ihohoterwa",
      quiz_desc: "Ihohoterwa si ugukubitwa gusa. Hitamo icyo ari cyo cyose gikurikira ukorera:",
      quiz_items: [
        "Ese uwo bashakanye cyangwa uwo mu muryango akukubita, akugusha cyangwa akukangisha?",
        "Ese ukorera imibonano mpuzabitsina ku ngufu cyangwa utabyemeye?",
        "Ese umuntu amfata amafaranga yawe yose, akakubuza gukora cyangwa akakwima ibyo kurya?",
        "Ese hora utukwa, ugabanyirizwa icyubahiro, cyangwa uburizwamo kubonana n'inshuti?",
        "Ese uri gukurikiranwa mu ibanga, kwatsindiwe ku mbuga nkoranyambaga cyangwa gukangishwa?"
      ],
      quiz_alert_title: "Niba wasubije EGO kuri kimwe muri ibi:",
      quiz_alert_desc: "Uri gukorerwa Ihohoterwa Rishingiye ku Gitsina. NTIURI WONYINE, kandi SI IKYAHA CYAWE. Ubufasha burahari ku buntu 24/7.",
      faq1_q: "Ese nshobora gutanga raporo ntarashaka kujya mu nkiko?",
      faq1_a: "Yego! Gutanga raporo kuri Vugana biha abakozi ba Isange fursa yo kuguha ubuvuzi n'inshunge utarinze kwitabaza inkiko niba utarabitegura.",
      faq2_q: "Ese Vugana yishyurwa amafaranga?",
      faq2_a: "Oya. Urubuga rwa Vugana ni 100% ku buntu kuri terefone n'iya mudasobwa.",
      faq3_q: "Biramutse bibaye ngombwa ko umuntu aza nko kureba terefone yanjye?",
      faq3_a: "Kanda ku butoni itukura 'Sohoka Wihuse' iri hejuru. Izahita ihindura screen ijye ku rubuga ruza rudafite aho ruhuriye n'ibi."
    },
    staff_portal: {
      title: "Ahabarizwa Abakozi ba Isange One Stop Centre",
      subtitle: "Ubwinjiriro bw'abakozi ba Isange (Social Workers, Medical staff, RIB Officers) kureba no gusubiza raporo z'uturere twabo.",
      passcode_label: "Shyiramo Ijambo ry'Ibanga ry'Abakozi:",
      passcode_placeholder: "Ijambo ry'ibanga: isange2026",
      login_btn: "Injira mu Dashbord",
      district_filter: "Gushungura Raporo ku Karere:",
      status_filter: "Gushungura ku Stero:",
      total_reports: "Igiteranyo cy'Ibyanditswe:",
      respond_title: "Andika Igisubizo n'Ubufasha wa Isange",
      message_label: "Ubutumwa n'Ibyakozwe k'Uwakorewe Ihohoterwa:",
      message_placeholder: "Urugero: Ubuvuzi bwatanzwe mu bitaro. Social worker yagenwe. Hamagara 116 niba ukeneye imbangukiragutabara.",
      status_update_label: "Hindura Aho Ikirego Kigeze:",
      submit_response_btn: "Ohereza Igisubizo ku Kode"
    }
  }
};
